"""empty message

Revision ID: 127ebd7955e7
Revises: 
Create Date: 2020-06-06 17:27:34.070832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127ebd7955e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('Authors', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.String(length=150), nullable=False),
    sa.Column('aromat', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('alt_txt', sa.String(length=250), nullable=True),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.Column('img', sa.String(length=248), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otziv', sa.String(length=250), nullable=True),
    sa.Column('authorOtziv', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('user_img', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('otdel', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('otzivy', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('revs')
    op.drop_table('products')
    # ### end Alembic commands ###
