"""empty message

Revision ID: 846c3383612b
Revises: a5b6f0809b06
Create Date: 2020-06-27 13:41:26.443445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846c3383612b'
down_revision = 'a5b6f0809b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart', 'products', ['productid'], ['id'])
    # ### end Alembic commands ###
