"""empty message

Revision ID: 933dbbb8e123
Revises: 7fb563cc6b35
Create Date: 2020-06-06 00:54:06.949210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933dbbb8e123'
down_revision = '7fb563cc6b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otziv', sa.String(length=250), nullable=True),
    sa.Column('authorOtziv', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('products', 'authorOtziv')
    op.drop_column('products', 'otziv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('otziv', sa.VARCHAR(length=250), nullable=True))
    op.add_column('products', sa.Column('authorOtziv', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('revs')
    # ### end Alembic commands ###
