"""empty message

Revision ID: aa88b135a655
Revises: 
Create Date: 2020-06-29 19:54:05.336323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa88b135a655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('Authors', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('aromat', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('characteristics', sa.Text(), nullable=False),
    sa.Column('alt_txt', sa.String(length=250), nullable=True),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.Column('img1', sa.String(length=248), nullable=True),
    sa.Column('img2', sa.String(length=248), nullable=True),
    sa.Column('img3', sa.String(length=248), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('user_img', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('otdel', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid', 'productid')
    )
    op.create_table('oders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('rebate', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otziv', sa.String(length=250), nullable=True),
    sa.Column('author', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revs')
    op.drop_table('oders')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
