"""empty message

Revision ID: e448bcd14459
Revises: 
Create Date: 2020-06-09 16:07:24.328549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e448bcd14459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revs', sa.Column('author', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revs', 'author')
    # ### end Alembic commands ###
