"""empty message

Revision ID: f69209ddb0ad
Revises: 85088a14be6e
Create Date: 2020-06-10 21:41:31.956400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69209ddb0ad'
down_revision = '85088a14be6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revs', sa.Column('img', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revs', 'img')
    # ### end Alembic commands ###
